openapi: '3.0.0'
info:
  title: 'Parallel API'
  description: |
    This is the documentation of the Parallel API. Used for the client application found [here.](https://para-llel.app)
  version: '1.0.0'
tags:
  - name: User
  - name: Channel
  - name: Block
  - name: Feed
    description: User feed or general feed when not logged in
servers:
  - url: "http://localhost:3000/api/v1"
    description: "Development server"
  - url: "https://api.para-llel.app/api/v1"
    description: "Production server"
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      description: Cookie session
      in: cookie
      name: sid.cookie
 