openapi: '3.0.0'
info:
  title: 'Parallel API'
  description: 'REST API for Parallel application.'
  version: '1.0.0'
tags:
  - name: User
    description: User
  - name: Channel
    description: Channel
  - name: Block
    description: Block
  - name: Follow
    description: Follow
  - name: Connection
    description: Connection
  - name: Feed
    description: Feed
servers:
  - url: "http://localhost:3000/api/v1"
    description: "Development server"
  - url: "api.para-llel.app/api/v1"
    description: "Production server"
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      description: Cookie session
      in: cookie
      name: sid.cookie  